version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"