name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v6
        
      - name: Build project
        run: npm run build
        env:
          VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}
          SLACK_URI:  ${{ secrets.SLACK_URI }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Specify the branch where GitHub Pages is hosted
          force_orphan: true       # Force to initialize the branch as an orphan
          cname: example.com       # Optional: Add a custom domain if needed
          
  send-slack-notification:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - name: Checkout repo (for context)
        uses: actions/checkout@v2

      - name: Get build logs
        id: build-logs
        run: cat ${{ github.workspace }}/path-to-your-build-log-file.log || echo "No build log found"

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
          text: ${{ steps.build-logs.outputs.build-log }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_URI }}


      
