name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v6
        
      - name: Build project
        run: npm run build
        env:
          VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}
          slack-webhook:  ${{ secrets.SLACK_URI }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_URI }} 
      
        if: always()

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Specify the branch where GitHub Pages is hosted
          force_orphan: true       # Force to initialize the branch as an orphan
          cname: example.com       # Optional: Add a custom domain if needed
          
  
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
           status: ${{ job.status }}
           mention: "here"
           author_name: "GitHub Actions"
        env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_URI }} 


      
